export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const FETCH_CATEGORY_DETAIL_REQUEST = 'FETCH_CATEGORY_DETAIL_REQUEST';
export const FETCH_CATEGORY_DETAIL_SUCCESS = 'FETCH_CATEGORY_DETAIL_SUCCESS';
export const FETCH_CATEGORY_DETAIL_FAILURE = 'FETCH_CATEGORY_DETAIL_FAILURE';

export const FETCH_LAWS_REQUEST = 'FETCH_LAWS_REQUEST';
export const FETCH_LAWS_SUCCESS = 'FETCH_LAWS_SUCCESS';
export const FETCH_LAWS_FAILURE = 'FETCH_LAWS_FAILURE';

export const FETCH_DEPARTMENTS_REQUEST = 'FETCH_DEPARTMENTS_REQUEST';
export const FETCH_DEPARTMENTS_SUCCESS = 'FETCH_DEPARTMENTS_SUCCESS';
export const FETCH_DEPARTMENTS_FAILURE = 'FETCH_DEPARTMENTS_FAILURE';
